/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPermissionManager } from "./IPermissionManager";

export { IPermissionManager__factory } from "./factories/IPermissionManager__factory";
