/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPermissionManagerInterface extends ethers.utils.Interface {
  functions: {
    "getUserPermissions(address)": FunctionFragment;
    "isInRole(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getUserPermissions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isInRole",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getUserPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isInRole", data: BytesLike): Result;

  events: {};
}

export class IPermissionManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPermissionManagerInterface;

  functions: {
    getUserPermissions(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber]>;

    "getUserPermissions(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber]>;

    isInRole(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isInRole(address,uint256)"(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getUserPermissions(
    user: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber]>;

  "getUserPermissions(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber]>;

  isInRole(
    user: string,
    role: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isInRole(address,uint256)"(
    user: string,
    role: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getUserPermissions(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber]>;

    "getUserPermissions(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber]>;

    isInRole(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isInRole(address,uint256)"(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getUserPermissions(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserPermissions(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInRole(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isInRole(address,uint256)"(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getUserPermissions(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserPermissions(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInRole(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isInRole(address,uint256)"(
      user: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
